/* Generated By:JJTree: Do not edit this line. ./eg4TreeConstants.java */

public interface eg4TreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTADD = 2;
  public int JJTMULT = 3;
  public int JJTMYOTHERID = 4;
  public int JJTINTEGER = 5;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "Add",
    "Mult",
    "MyOtherID",
    "Integer",
  };
}
