/* Generated By:JJTree: Do not edit this line. ASTAddNode.java */

public class ASTAddNode extends SimpleNode {
  public ASTAddNode(int id) {
    super(id);
  }

  public ASTAddNode(SPLParser p, int id) {
    super(p, id);
  }

}
