/* Generated By:JJTree: Do not edit this line. ASTAndNode.java */

public class ASTAndNode extends SimpleNode {
  public ASTAndNode(int id) {
    super(id);
  }

  public ASTAndNode(SPLParser p, int id) {
    super(p, id);
  }

}
