/* Generated By:JJTree: Do not edit this line. ASTBitwiseXorNode.java */

public class ASTBitwiseXorNode extends SimpleNode {
  public ASTBitwiseXorNode(int id) {
    super(id);
  }

  public ASTBitwiseXorNode(SPLParser p, int id) {
    super(p, id);
  }

}
