/* Generated By:JJTree: Do not edit this line. ASTBitwiseAndNode.java */

public class ASTBitwiseAndNode extends SimpleNode {
  public ASTBitwiseAndNode(int id) {
    super(id);
  }

  public ASTBitwiseAndNode(SPLParser p, int id) {
    super(p, id);
  }

}
