/* Generated By:JJTree: Do not edit this line. ASTBitwiseOrNode.java */

public class ASTBitwiseOrNode extends SimpleNode {
  public ASTBitwiseOrNode(int id) {
    super(id);
  }

  public ASTBitwiseOrNode(SPLParser p, int id) {
    super(p, id);
  }

}
