/* Generated By:JJTree: Do not edit this line. ASTBitwiseComplNode.java */

public class ASTBitwiseComplNode extends SimpleNode {
  public ASTBitwiseComplNode(int id) {
    super(id);
  }

  public ASTBitwiseComplNode(SPLParser p, int id) {
    super(p, id);
  }

}
