/* Generated By:JJTree: Do not edit this line. ASTDivNode.java */

public class ASTDivNode extends SimpleNode {
  public ASTDivNode(int id) {
    super(id);
  }

  public ASTDivNode(SPLParser p, int id) {
    super(p, id);
  }

}
