/* Generated By:JJTree: Do not edit this line. ASTEQNode.java */

public class ASTEQNode extends SimpleNode {
  public ASTEQNode(int id) {
    super(id);
  }

  public ASTEQNode(SPLParser p, int id) {
    super(p, id);
  }

}
