/* Generated By:JJTree: Do not edit this line. ASTFalseNode.java */

public class ASTFalseNode extends SimpleNode {
  public ASTFalseNode(int id) {
    super(id);
  }

  public ASTFalseNode(SPLParser p, int id) {
    super(p, id);
  }

}
