/* Generated By:JJTree: Do not edit this line. ASTGENode.java */

public class ASTGENode extends SimpleNode {
  public ASTGENode(int id) {
    super(id);
  }

  public ASTGENode(SPLParser p, int id) {
    super(p, id);
  }

}
