/* Generated By:JJTree: Do not edit this line. ASTGTNode.java */

public class ASTGTNode extends SimpleNode {
  public ASTGTNode(int id) {
    super(id);
  }

  public ASTGTNode(SPLParser p, int id) {
    super(p, id);
  }

}
