/* Generated By:JJTree: Do not edit this line. ASTId.java */

public class ASTId extends SimpleNode {
  public ASTId(int id) {
    super(id);
  }

  public ASTId(SPLParser p, int id) {
    super(p, id);
  }

}
