/* Generated By:JJTree: Do not edit this line. ASTIntConstNode.java */

public class ASTIntConstNode extends SimpleNode {
  public ASTIntConstNode(int id) {
    super(id);
  }

  public ASTIntConstNode(SPLParser p, int id) {
    super(p, id);
  }

}
