/* Generated By:JJTree: Do not edit this line. ASTLENode.java */

public class ASTLENode extends SimpleNode {
  public ASTLENode(int id) {
    super(id);
  }

  public ASTLENode(SPLParser p, int id) {
    super(p, id);
  }

}
