/* Generated By:JJTree: Do not edit this line. ASTLTNode.java */

public class ASTLTNode extends SimpleNode {
  public ASTLTNode(int id) {
    super(id);
  }

  public ASTLTNode(SPLParser p, int id) {
    super(p, id);
  }

}
