/* Generated By:JJTree: Do not edit this line. ASTMulNode.java */

public class ASTMulNode extends SimpleNode {
  public ASTMulNode(int id) {
    super(id);
  }

  public ASTMulNode(SPLParser p, int id) {
    super(p, id);
  }

}
