/* Generated By:JJTree: Do not edit this line. ASTModNode.java */

public class ASTModNode extends SimpleNode {
  public ASTModNode(int id) {
    super(id);
  }

  public ASTModNode(SPLParser p, int id) {
    super(p, id);
  }

}
