/* Generated By:JJTree: Do not edit this line. ASTNENode.java */

public class ASTNENode extends SimpleNode {
  public ASTNENode(int id) {
    super(id);
  }

  public ASTNENode(SPLParser p, int id) {
    super(p, id);
  }

}
