/* Generated By:JJTree: Do not edit this line. ASTNotNode.java */

public class ASTNotNode extends SimpleNode {
  public ASTNotNode(int id) {
    super(id);
  }

  public ASTNotNode(SPLParser p, int id) {
    super(p, id);
  }

}
