/* Generated By:JJTree: Do not edit this line. ASTOrNode.java */

public class ASTOrNode extends SimpleNode {
  public ASTOrNode(int id) {
    super(id);
  }

  public ASTOrNode(SPLParser p, int id) {
    super(p, id);
  }

}
