/* Generated By:JJTree: Do not edit this line. ASTSubtractNode.java */

public class ASTSubtractNode extends SimpleNode {
  public ASTSubtractNode(int id) {
    super(id);
  }

  public ASTSubtractNode(SPLParser p, int id) {
    super(p, id);
  }

}
