/* Generated By:JJTree: Do not edit this line. ASTTrueNode.java */

public class ASTTrueNode extends SimpleNode {
  public ASTTrueNode(int id) {
    super(id);
  }

  public ASTTrueNode(SPLParser p, int id) {
    super(p, id);
  }

}
