/* Generated By:JJTree: Do not edit this line. ASTInteger.java */

public class ASTInteger extends SimpleNode {
  public ASTInteger(int id) {
    super(id);
  }

  public ASTInteger(eg2 p, int id) {
    super(p, id);
  }

}
