/* Generated By:JJTree: Do not edit this line. ASTAdd.java */

public class ASTAdd extends SimpleNode {
  public ASTAdd(int id) {
    super(id);
  }

  public ASTAdd(eg3 p, int id) {
    super(p, id);
  }

}
