/* Generated By:JJTree: Do not edit this line. ASTMult.java */

public class ASTMult extends SimpleNode {
  public ASTMult(int id) {
    super(id);
  }

  public ASTMult(eg3 p, int id) {
    super(p, id);
  }

}
