/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package  edu.ustc.cs.compile.skipoominijool;

public interface ParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 8;
  int FORMAL_COMMENT = 9;
  int MULTI_LINE_COMMENT = 10;
  int PROGRAM = 12;
  int CLASS = 13;
  int INT = 14;
  int BOOLEAN = 15;
  int STRING = 16;
  int IF = 17;
  int ELSE = 18;
  int WHILE = 19;
  int CONTINUE = 20;
  int BREAK = 21;
  int STATIC = 22;
  int FINAL = 23;
  int VOID = 24;
  int RETURN = 25;
  int READ = 26;
  int PRINT = 27;
  int INTEGER_LITERAL = 28;
  int DECIMAL_LITERAL = 29;
  int HEX_LITERAL = 30;
  int OCTAL_LITERAL = 31;
  int STRING_LITERAL = 32;
  int TRUE = 33;
  int FALSE = 34;
  int LENGTH = 35;
  int IDENTIFIER = 36;
  int LINE_LETTER = 37;
  int DIGIT_LINE_LETTER = 38;
  int LPAREN = 39;
  int RPAREN = 40;
  int LBRACE = 41;
  int RBRACE = 42;
  int LBRACKET = 43;
  int RBRACKET = 44;
  int SEMICOLON = 45;
  int COMMA = 46;
  int DOT = 47;
  int ASSIGN = 48;
  int LT = 49;
  int GT = 50;
  int BANG = 51;
  int EQ = 52;
  int LE = 53;
  int GE = 54;
  int NE = 55;
  int OR = 56;
  int AND = 57;
  int INCR = 58;
  int DECR = 59;
  int PLUS = 60;
  int MINUS = 61;
  int STAR = 62;
  int SLASH = 63;
  int REM = 64;
  int PLUSASSIGN = 65;
  int MINUSASSIGN = 66;
  int STARASSIGN = 67;
  int SLASHASSIGN = 68;
  int REMASSIGN = 69;

  int DEFAULT = 0;
  int IN_FORMAL_COMMENT = 1;
  int IN_MULTI_LINE_COMMENT = 2;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<token of kind 6>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 11>",
    "\"Program\"",
    "\"class\"",
    "\"int\"",
    "\"boolean\"",
    "\"String\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"continue\"",
    "\"break\"",
    "\"static\"",
    "\"final\"",
    "\"void\"",
    "\"return\"",
    "\"read\"",
    "\"print\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<STRING_LITERAL>",
    "\"true\"",
    "\"false\"",
    "\"length\"",
    "<IDENTIFIER>",
    "<LINE_LETTER>",
    "<DIGIT_LINE_LETTER>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\"<\"",
    "\">\"",
    "\"!\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"%=\"",
  };

}
